//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyKanji
    {
        public long C_key { get; set; }
        public string C_index { get; set; }
        public string C_kanji { get; set; }
        public string C_pronunciation { get; set; }
        public string C_chinese { get; set; }
        public string C_example { get; set; }
        public Nullable<int> C_didRemember { get; set; }
        public Nullable<long> C_groupid { get; set; }
    }
}
