//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCard.Asset {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Font {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Font() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashCard.Asset.Font", typeof(Font).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handwriting.ttf#MogihaPenFont.
        /// </summary>
        internal static string Handwriting_ttf {
            get {
                return ResourceManager.GetString("Handwriting.ttf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KanjiStrokeOrders.ttf#KanjiStrokeOrders.
        /// </summary>
        internal static string KanjiStrokeOrders_ttf {
            get {
                return ResourceManager.GetString("KanjiStrokeOrders.ttf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahoma.ttf#Tahoma.
        /// </summary>
        internal static string Tahoma_ttf {
            get {
                return ResourceManager.GetString("Tahoma.ttf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeNewRoman.ttf#Times New Roman.
        /// </summary>
        internal static string TimeNewRoman_ttf {
            get {
                return ResourceManager.GetString("TimeNewRoman.ttf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教科書体.TTF#EPSON ã≥â»èëëÃÇl.
        /// </summary>
        internal static string 教科書体_TTF {
            get {
                return ResourceManager.GetString("教科書体.TTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 楷書体.TTF#EPSON ê≥û≤èëëÃÇl.
        /// </summary>
        internal static string 楷書体_TTF {
            get {
                return ResourceManager.GetString("楷書体.TTF", resourceCulture);
            }
        }
    }
}
